<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Configuration\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Logging\" />
    <Folder Include="Models\" />
    <Folder Include="Services\" />
    <Folder Include="Security\" />
  </ItemGroup>

</Project>
